name: Nightly build and test

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

on:
  schedule:
    - cron: '42 0 * * *'

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
