name: Merge or commit

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: swift-actions/setup-swift@v1
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
